kind: Template
apiVersion: v1
metadata:
  name: blast-scraper-template
  annotations:
    description: This example shows how to create application containing multiple micoroservices in openshift origin v3
    iconClass: icon-python
labels:
  template: blast-scraper
objects:
  #
  # cron job
  #
  - apiVersion: batch/v2alpha1
    kind: CronJob
    metadata:
      labels:
        run: scraper
      name: scraper
    spec:
      schedule: 0/5 * * * *
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                run: scraper
            spec:
              containers:
              - image: soltysh/scraper
                imagePullPolicy: Always
                name: scraper
              restartPolicy: Never
              serviceAccountName: scraper
  #
  # build configuration
  #
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: scraper
      labels:
        name: scraper
    spec:
      triggers:
        - type: GitHub
          github:
            secret: "${GITHUB_SECRET}"
        - type: Generic
          generic:
            secret: "${GENERIC_SECRET}"
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: https://github.com/soltysh/blast.git
        contextDir: scraper
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:latest
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: scraper:latest
  #
  # image stream configuration
  #
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: scraper
#
# template parameters generation configuration
#
parameters:
  - name: GITUB_SECRET
    description: github webhook secret
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
  - name: GENERIC_SECRET
    description: generic webhook secret
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
