kind: Template
apiVersion: v1
metadata:
  name: openshift-microservices
  annotations:
    description: This example shows how to create application containing multiple micoroservices in openshift origin v3
    iconClass: icon-python
labels:
  template: openshift-microservices-template
objects:
  #
  # build configuration
  #
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ui
      labels:
        name: ui
    spec:
      triggers:
        - type: GitHub
          github:
            secret: "${GITHUB_SECRET}"
        - type: Generic
          generic:
            secret: "${GENERIC_SECRET}"
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: https://github.com/soltysh/blast.git
        contextDir: ui
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: DockerImage
            name: soltysh/lighttpd-centos7
      output:
        to:
          kind: ImageStreamTag
          name: ui:latest
  #
  # image stream configuration
  #
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ui
  #
  # deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ui
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ui
            from:
              kind: ImageStreamTag
              name: ui:latest
        - type: ConfigChange
      replicas: 1
      selector:
        name: ui
      template:
        metadata:
          labels:
            name: ui
        spec:
          containers:
            - name: ui
              image: ui
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: ui
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: ui
  #
  # route configuration
  #
  - kind: Route
    apiVersion: v1
    metadata:
      name: ui
    spec:
      to:
        kind: Service
        name: ui
#
# template parameters generation configuration
#
parameters:
  - name: GITUB_SECRET
    description: github webhook secret
    generate: expression
    from: "[A-Z0-9]{16}"
    required: true
  - name: GENERIC_SECRET
    description: generic webhook secret
    generate: expression
    from: "[A-Z0-9]{16}"
    required: true
